version: "3"
services:
  php71:
    build: ./docker/php71
    volumes:
      - .:/var/www/html
      - ./docker/php71/php-fpm.conf:/usr/local/etc/php-fpm.conf
    networks:
      - backend

  web:
    image: nginx:1.13-alpine
    ports:
      - "80:80"
      - "443:443"
    networks:
      - backend
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./docker/nginx/ssl:/etc/nginx/ssl
      - ./docker/nginx/spryker:/etc/nginx/spryker
      - .:/var/www/html
    depends_on:
      - php71

networks:
  backend:

volumes:
  dbdata:
  appdata:
