version: "3"
services:
  php71:
    build: ./docker/php71
    volumes:
      - .:/var/www/html
      - ./docker/php71/php-fpm.conf:/usr/local/etc/php-fpm.conf
    networks:
      - backend

networks:
  backend:

volumes:
  dbdata: